/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-11-12 02:36:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/55499/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c-1_0.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("file:/C:/Users/55499/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1603757410361L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.lang.String title;

  public java.lang.String getTitle() {
    return this.title;
  }

  public void setTitle(java.lang.String title) {
    this.title = title;
    jspContext.setAttribute("title", title);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getTitle() != null ) 
      _jspx_page_context.setAttribute("title", getTitle());

    try {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"header-content\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand\">\r\n");
      out.write("            <div class=\"collapse navbar-collapse justify-content-between\">\r\n");
      out.write("                <div class=\"header-left\">\r\n");
      out.write("                    <div class=\"search_bar dropdown show\">\r\n");
      out.write("                        <div class=\"dropdown-menu p-0 m-0 show\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"navbar-nav header-right\">\r\n");
      out.write("                    <li class=\"nav-item dropdown notification_dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dz-fullscreen primary\" href=\"#\">\r\n");
      out.write("                            <svg id=\"Capa_1\" enable-background=\"new 0 0 482.239 482.239\" height=\"22\" viewBox=\"0 0 482.239 482.239\" width=\"22\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"m0 17.223v120.56h34.446v-103.337h103.337v-34.446h-120.56c-9.52 0-17.223 7.703-17.223 17.223z\" fill=\"\"/><path d=\"m465.016 0h-120.56v34.446h103.337v103.337h34.446v-120.56c0-9.52-7.703-17.223-17.223-17.223z\" fill=\"\"/><path d=\"m447.793 447.793h-103.337v34.446h120.56c9.52 0 17.223-7.703 17.223-17.223v-120.56h-34.446z\" fill=\"\" /><path d=\"m34.446 344.456h-34.446v120.56c0 9.52 7.703 17.223 17.223 17.223h120.56v-34.446h-103.337z\" fill=\"\"/></svg>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"nav-item dropdown notification_dropdown\">\r\n");
      out.write("                        <a class=\"nav-link  ai-icon warning\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\r\n");
      out.write("                            <svg width=\"24\" height=\"24\" viewBox=\"0 0 26 26\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M21.75 14.8385V12.0463C21.7471 9.88552 20.9385 7.80353 19.4821 6.20735C18.0258 4.61116 16.0264 3.61555 13.875 3.41516V1.625C13.875 1.39294 13.7828 1.17038 13.6187 1.00628C13.4546 0.842187 13.2321 0.75 13 0.75C12.7679 0.75 12.5454 0.842187 12.3813 1.00628C12.2172 1.17038 12.125 1.39294 12.125 1.625V3.41534C9.97361 3.61572 7.97429 4.61131 6.51794 6.20746C5.06159 7.80361 4.25291 9.88555 4.25 12.0463V14.8383C3.26257 15.0412 2.37529 15.5784 1.73774 16.3593C1.10019 17.1401 0.751339 18.1169 0.75 19.125C0.750764 19.821 1.02757 20.4882 1.51969 20.9803C2.01181 21.4724 2.67904 21.7492 3.375 21.75H8.71346C8.91521 22.738 9.45205 23.6259 10.2331 24.2636C11.0142 24.9013 11.9916 25.2497 13 25.2497C14.0084 25.2497 14.9858 24.9013 15.7669 24.2636C16.548 23.6259 17.0848 22.738 17.2865 21.75H22.625C23.321 21.7492 23.9882 21.4724 24.4803 20.9803C24.9724 20.4882 25.2492 19.821 25.25 19.125C25.2486 18.117 24.8998 17.1402 24.2622 16.3594C23.6247 15.5786 22.7374 15.0414 21.75 14.8385ZM6 12.0463C6.00232 10.2113 6.73226 8.45223 8.02974 7.15474C9.32723 5.85726 11.0863 5.12732 12.9212 5.125H13.0788C14.9137 5.12732 16.6728 5.85726 17.9703 7.15474C19.2677 8.45223 19.9977 10.2113 20 12.0463V14.75H6V12.0463ZM13 23.5C12.4589 23.4983 11.9316 23.3292 11.4905 23.0159C11.0493 22.7026 10.716 22.2604 10.5363 21.75H15.4637C15.284 22.2604 14.9507 22.7026 14.5095 23.0159C14.0684 23.3292 13.5411 23.4983 13 23.5ZM22.625 20H3.375C3.14298 19.9999 2.9205 19.9076 2.75644 19.7436C2.59237 19.5795 2.50014 19.357 2.5 19.125C2.50076 18.429 2.77757 17.7618 3.26969 17.2697C3.76181 16.7776 4.42904 16.5008 5.125 16.5H20.875C21.571 16.5008 22.2382 16.7776 22.7303 17.2697C23.2224 17.7618 23.4992 18.429 23.5 19.125C23.4999 19.357 23.4076 19.5795 23.2436 19.7436C23.0795 19.9076 22.857 19.9999 22.625 20Z\" fill=\"#000\"/></svg>\r\n");
      out.write("                            <div class=\"pulse-css\"></div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                            <div id=\"DZ_W_Notification1\" class=\"widget-media dz-scroll p-3\" style=\"height:380px;\">\r\n");
      out.write("                                <ul class=\"timeline\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"timeline-panel\">\r\n");
      out.write("                                            <div class=\"media mr-2\">\r\n");
      out.write("                                                <img alt=\"image\" width=\"50\" src=\"images/avatar/1.jpg\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h6 class=\"mb-1\">Dr sultads Send you Photo</h6>\r\n");
      out.write("                                                <small class=\"d-block\">29 July 2020 - 02:26 PM</small>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"timeline-panel\">\r\n");
      out.write("                                            <div class=\"media mr-2 media-info\">\r\n");
      out.write("                                                KG\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h6 class=\"mb-1\">Resport created successfully</h6>\r\n");
      out.write("                                                <small class=\"d-block\">29 July 2020 - 02:26 PM</small>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"timeline-panel\">\r\n");
      out.write("                                            <div class=\"media mr-2 media-success\">\r\n");
      out.write("                                                <i class=\"fa fa-home\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h6 class=\"mb-1\">Reminder : Treatment Time!</h6>\r\n");
      out.write("                                                <small class=\"d-block\">29 July 2020 - 02:26 PM</small>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"timeline-panel\">\r\n");
      out.write("                                            <div class=\"media mr-2\">\r\n");
      out.write("                                                <img alt=\"image\" width=\"50\" src=\"images/avatar/1.jpg\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h6 class=\"mb-1\">Dr sultads Send you Photo</h6>\r\n");
      out.write("                                                <small class=\"d-block\">29 July 2020 - 02:26 PM</small>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"timeline-panel\">\r\n");
      out.write("                                            <div class=\"media mr-2 media-danger\">\r\n");
      out.write("                                                KG\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h6 class=\"mb-1\">Resport created successfully</h6>\r\n");
      out.write("                                                <small class=\"d-block\">29 July 2020 - 02:26 PM</small>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"timeline-panel\">\r\n");
      out.write("                                            <div class=\"media mr-2 media-primary\">\r\n");
      out.write("                                                <i class=\"fa fa-home\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h6 class=\"mb-1\">Reminder : Treatment Time!</h6>\r\n");
      out.write("                                                <small class=\"d-block\">29 July 2020 - 02:26 PM</small>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"all-notification\" href=\"#\">See all notifications <i class=\"ti-arrow-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown header-profile\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\r\n");
      out.write("                            <div class=\"header-info\">\r\n");
      out.write("                                <span>Ola, <strong>Usuario</strong></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"https://png.pngtree.com/png-vector/20191110/ourmid/pngtree-avatar-icon-profile-icon-member-login-vector-isolated-png-image_1978396.jpg\" width=\"20\" alt=\"\"/>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                            <a href=\"app-profile.html\" class=\"dropdown-item ai-icon\">\r\n");
      out.write("                                <svg id=\"icon-user1\" xmlns=\"http://www.w3.org/2000/svg\" class=\"text-primary\" width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"></path><circle cx=\"12\" cy=\"7\" r=\"4\"></circle></svg>\r\n");
      out.write("                                <span class=\"ml-2\">Profile </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"email-inbox.html\" class=\"dropdown-item ai-icon\">\r\n");
      out.write("                                <svg id=\"icon-inbox\" xmlns=\"http://www.w3.org/2000/svg\" class=\"text-success\" width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z\"></path><polyline points=\"22,6 12,13 2,6\"></polyline></svg>\r\n");
      out.write("                                <span class=\"ml-2\">Inbox </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"page-login.html\" class=\"dropdown-item ai-icon\">\r\n");
      out.write("                                <svg id=\"icon-logout\" xmlns=\"http://www.w3.org/2000/svg\" class=\"text-danger\" width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4\"></path><polyline points=\"16 17 21 12 16 7\"></polyline><line x1=\"21\" y1=\"12\" x2=\"9\" y2=\"12\"></line></svg>\r\n");
      out.write("                                <span class=\"ml-2\">Logout </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
